# Generated by Django 3.2 on 2021-04-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('explicacion', models.TextField(max_length=500)),
                ('terminada', models.BooleanField()),
                ('fecha', models.DateField()),
            ],
        ),
    ]
