# Generated by Django 3.2.3 on 2021-05-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escobas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.IntegerField(max_length=20)),
                ('explicacion', models.TextField(max_length=500)),
                ('archivada', models.BooleanField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
