# Generated by Django 3.2.3 on 2021-05-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escobas', '0003_auto_20210524_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='archivada',
            field=models.BooleanField(default=False),
        ),
    ]
