# Generated by Django 3.2.3 on 2021-05-24 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escobas', '0004_alter_mensaje_archivada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='archivada',
            new_name='archivado',
        ),
    ]
